version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: latest
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - echo $ENVIRONMENT Install started on `date`
      - npm install
      - npm i webpack-cli
      - apt-get install jq
      - export NPM_TOKEN=$NPM_TOKEN
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - LATEST=$( npm view @paytheory/pay-theory-ui  versions --json | jq -r '.[-1]')
      - npm version ${LATEST} --allow-same-version
      - npm version prepatch
      - npm publish --tag $ENVIRONMENT